import { Box, Typography } from '@mui/material';
import { faChevronRight } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { FeaturedPools, InfoChart, PoolsTable, TokensTable, TransactionsTable } from 'components';
import { OverviewComponentStyle } from './index.style';
import { useMemo, useState } from 'react';
import { createMockChartInfo, mockPoolDetails, mockTokenDetails } from '__mock__';
import { NextRouter } from 'next/dist/client/router';

export interface IOverviewComponentProps {
  router: NextRouter,
}

export const OverviewComponent: React.FC<IOverviewComponentProps> = (props) => {
  const { router } = props;

  const chartData = useMemo(() => {
    return createMockChartInfo();
  }, []);

  const onSelectPool = (id: string) => {
    router.push(`?poolId=${id}`);
  };

  const onSelectToken = (id: string) => {
    router.push(`?tokenId=${id}`);
  };

  // pools table control
  const [isAsc, setAsc] = useState<boolean>();
  const [sortKey, setSortKey] = useState<string>('');

  const pools = useMemo(() => {
    return mockPoolDetails
      .slice(0, 9)
      .sort((a: any, b: any) => isAsc ? a[sortKey] - b[sortKey] : b[sortKey] - a[sortKey]);
  }, [sortKey, isAsc]);

  const onSortClick = (key: string) => {
    if (key !== sortKey) {
      setAsc(false);
      setSortKey(key);
    } else {
      setAsc(!isAsc);
    }
  };

  // tokens table control
  const [isTokenAsc, setTokenAsc] = useState<boolean>();
  const [sortTokenKey, setSortTokenKey] = useState<string>('');

  const tokens = useMemo(() => {
    return mockTokenDetails
      .sort((a: any, b: any) => isTokenAsc ? a[sortTokenKey] - b[sortTokenKey] : b[sortTokenKey] - a[sortTokenKey]);
  }, [sortTokenKey, isTokenAsc]);

  const onSortTokenClick = (key: string) => {
    if (key !== sortTokenKey) {
      setTokenAsc(false);
      setSortTokenKey(key);
    } else {
      setTokenAsc(!isAsc);
    }
  };

  return (
    <OverviewComponentStyle>
      <Box className="info-header">
        <Typography variant="subtitle1">Overview</Typography>
        <Typography variant="body1">View and track liquidity, volume and fees generated by the Lisk decentralized exchange.</Typography>
      </Box>

      <InfoChart chartData={chartData} />

      <Box className="table-title">
        <Typography variant="subtitle1">Featured Pools</Typography>
      </Box>
      <FeaturedPools onSelectPool={onSelectPool} />

      <Box className="table-title">
        <Typography variant="subtitle1">Top Tokens</Typography>
        <Box className="view-all">
          <Typography variant="body2">View all tokens</Typography>
          <FontAwesomeIcon icon={faChevronRight} />
        </Box>
      </Box>
      <TokensTable
        tokens={tokens}
        isAsc={isTokenAsc}
        sortKey={sortTokenKey}
        onSortClick={onSortTokenClick}
        onSelectToken={onSelectToken}
      />


      <Box className="table-title">
        <Typography variant="subtitle1">Top Pools</Typography>
        <Box className="view-all">
          <Typography variant="body2">View all tokens</Typography>
          <FontAwesomeIcon icon={faChevronRight} />
        </Box>
      </Box>
      <PoolsTable
        pools={pools}
        onSortClick={onSortClick}
        onSelectPool={onSelectPool}
        sortKey={sortKey}
        isAsc={isAsc}
      />

      <Box className="table-title">
        <Typography variant="subtitle1">Transactions</Typography>
      </Box>
      <TransactionsTable />
    </OverviewComponentStyle>
  );
};