import { faChevronRight } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { Box, Tab, Tabs, Typography } from '@mui/material';
import { SearchInputComponent } from 'components/common';
import { useState } from 'react';
import { FeaturedPools } from './FeaturedPools';
import { InfoViewStyle } from './index.style';
import { InfoChart } from './InfoChart';
import { PoolsTable } from './PoolsTable';
import { TokensTable } from './TokensTable';
import { TransactionsTable } from './TransactionsTable';

export const InfoView: React.FC = () => {

  const [value, setValue] = useState(0);

  const handleChange = (event: React.SyntheticEvent, newValue: number) => {
    setValue(newValue);
  };

  return (
    <InfoViewStyle>
      <Box className="info-top-box">
        <Tabs className="info-tab" value={value} onChange={handleChange} centered>
          <Tab label="Overview" />
          <Tab label="Pools" />
          <Tab label="Tokens" />
        </Tabs>
        <SearchInputComponent
          className="info-search-box"
          placeholder="Search tokens or pools..."
        />
      </Box>

      <Box className="info-header">
        <Typography variant="subtitle1">Overview</Typography>
        <Typography variant="body1">View and track liquidity, volume and fees generated by the Lisk decentralized exchange.</Typography>
      </Box>

      <InfoChart />

      <Box className="table-title">
        <Typography variant="subtitle1">Featured Pools</Typography>
      </Box>
      <FeaturedPools />

      <Box className="table-title">
        <Typography variant="subtitle1">Top Tokens</Typography>
        <Box className="view-all">
          <Typography variant="body2">View all tokens</Typography>
          <FontAwesomeIcon icon={faChevronRight} />
        </Box>
      </Box>
      <TokensTable />

      <Box className="table-title">
        <Typography variant="subtitle1">Top Pools</Typography>
        <Box className="view-all">
          <Typography variant="body2">View all tokens</Typography>
          <FontAwesomeIcon icon={faChevronRight} />
        </Box>
      </Box>
      <PoolsTable />

      <Box className="table-title">
        <Typography variant="subtitle1">Transactions</Typography>
      </Box>
      <TransactionsTable />
    </InfoViewStyle>
  );
};