name: STG-DEX-UI ##change based on environment eg: staging or Production
on:
  push: ## for auto build when code triggered in below branch
    branches: 
        - cicdpipeline
  workflow_dispatch:
jobs:
  build:
    name: DEX-UI Deploy
    runs-on: ubuntu-20.04  # already has preinstalled Node 14.17.0
    strategy:
      matrix:
        node-version: [14.18.1]
    env: ## ----> Change below values <---- ##
      DISTRIBUTION_ID_FE: EKR65H62LQOX6
      BUCKET_NAME: lc-stg-lisk-dex-ui
      ## ----> modify end section <---- ## 
    steps:
      - uses: actions/checkout@v2
      # - uses: ./.github/actions/set-job-env //for later use.

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: |
          yarn install

      - name: Build
        run: |
          yarn run build

      - name: Configure AWS cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy DEX-UI
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ env.BUCKET_NAME }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          SOURCE_DIR: "./dist"

      - name: Invalidate CF
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ env.DISTRIBUTION_ID_FE }} --paths '/*'